### ISSUE TITLE
/pay

### ISSUE THREAD

**Issue by superjacobl** [Coca16/CocaBot#4]
CocaBot lacks a /pay command.
I demand that you add one

**Comment by Coca162** [comment]
fuck off

**Comment by superjacobl** [comment]
coca its easy

**Comment by Coca162** [comment]
no!

**Comment by superjacobl** [comment]
coca add a API

**Comment by Coca162** [comment]
FECK OFF

**Comment by Coca162** [comment]
Done!

**Comment by YahooCar** [comment]
hmmm

**Comment by superjacobl** [comment]
amazing

**Comment by YahooCar** [comment]
> fuck off

poggers

**Comment by ghost** [comment]
yo jabic

**Comment by ghost** [comment]
> > fuck off
> 
> poggers

indeed lmao

**Comment by Coca162** [comment]
> >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > > poggers?

**Comment by Coca162** [comment]
> >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > >  > > pogchamp?

**Comment by ghost** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> poggers indeed
